require:
  - rubocop-rspec
  - rubocop-performance

inherit_gem:
  rentacop:
    - rentacop.yml
    - rspec.yml

# Merge `Exclude` arrays
inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  Exclude:
    - 'dev/**/*'

# There is a special use case that needs this
Lint/LiteralAsCondition:
  Exclude:
    - 'spec/**/*'

# `SVGBase#element` is a bit complex
Metrics/PerceivedComplexity:
  Max: 11

# This test is allowed to use `eval`
Security/Eval:
  Exclude:
    - spec/victor/script_spec.rb

# Allow `include Victor` in some places
Style/MixinUsage:
  Exclude:
    - lib/victor/script.rb

# We use Marshal.load to test that it *can* be done. Allow it.
Security/MarshalLoad:
  Exclude:
    - spec/victor/svg_marshaling_spec.rb

RSpec/ExampleLength:
  Exclude:
    - spec/victor/svg_spec.rb
